version: '3'
services:
    adguardhome: 
      container_name: adguardhome
      image: adguard/adguardhome:latest
      volumes:
        - ./data/work:/opt/adguardhome/work
        - ./data/conf:/opt/adguardhome/conf
      networks:
        adguard:
          ipv4_address: 172.2.0.10
      ports:
          - 53:53/tcp
          - 53:53/udp
          - 3000:3000/tcp
            #- 784:784/tcp
            #- 784:784/udp
          - 3080:80/tcp
          - 853:853/tcp
          - 853:853/udp
          - 8853:8853/tcp
          - 8853:8853/udp
      restart: unless-stopped
networks:
  adguard:
    driver: bridge
    ipam:
      config:
        - subnet: 172.2.0.0/24
          gateway: 172.2.0.1
